# Generated by Django 5.0.7 on 2024-07-25 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publicity',
            field=models.CharField(choices=[('public', 'Public (everyone)'), ('authenticated', 'Authenticated (logged in users)'), ('private', 'Private (only me)')], default='public', max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question'),
        ),
    ]
